apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-app
  template:
    metadata:
      labels:
        app: helm-app
    spec:
      containers:
      - name: helm-app
        image: {{ .Values.demoImage }}
        ports:
        - containerPort: 80
        env:
        - name: DEMO_VALUE
          value: {{ .Values.demoValue }}
