apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefixName }}app{{ .Values.suffixName }}
  namespace: {{ .Values.prefixName }}ns{{ .Values.suffixName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: {{ .Values.demoImage }}
          ports:
            - containerPort: 80
          {{- with .Values.environment }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
