apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefixName }}svc{{ .Values.suffixName }}
  namespace: {{ .Values.prefixName }}ns{{ .Values.suffixName }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app