apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: docker.io/ealen/echo-server:0.4.3
        ports:
        - containerPort: 80
        env:
          - name: K8S_APP
            value: demoapp
