apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#
# Base Resources
#
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secret.yaml

namespace: k8s-ns-desa

namePrefix: k8s-
nameSuffix: -desa

configurations:
- kustomization-config.yaml
