---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret
spec:
  encryptedData:
    secreto: AgCXxsdwxe5HKCnGAmWcdsWjFoRo2nj5V2y2RqVZFjbB5P1CqqRscllQZ87rtfSSl8bBSuIf4hZIk3Kz4iW3cAvJu1GreujHCFai0FDdGACADQM8IaLbNSr4W/KpTCg6XHES30P6d162ySS7NzSgMQY6yN0QcWg45iuTJF04STfC/ScFlIWGvO09E+l2b1zpkmrMAQqzezCrmNMpdP6KGH3h5qlZS0PoOkcl3TNv+vG4c3vgyIr7A6ZkjydKf5sYtyIJgYABXJdnUrQDHAJ05aCR469zQkprul1G0qMJjhHZOMJhD3jHQS2N+yxe9MSo09l9BwVQFOAubnuLSq3FE0PvnThbjZ35W4rCfKE1oeTO+XxlMH8n4qZWLSO5lwVNnYOCorVKXXY9sD8VdQ4rk2CkNRU8F8VOSRTzAzjpUMWhiE3hYaO3dMsVspHrLyGUQbKBxP01i5ZK1EFoQ82e4VkZcUh70hsynXCt6gaxncLyXYTW8j29wjd+RNBr974TELTltkPuwuFNtYLAHosQXDtnn17p40bnL6Q71773NHZnyek6Lh4F4F3k9bjhupwoTaXqtfWPMgkKcs+JMg/j2tWPJ0/726BPuPWCc/jmyp1HX9EzFAv9VAqOT6nBdALenoDTkyGEAEd0xKOC8jvXuYgjJ75tSMNVC3yHFYCHTZamLrxSgzuP3CZUifGsFygrEh+rvcOfEnZwRcvD
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret
    type: Opaque