apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helmapp
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: default
  chart:
    spec:
      chart: ./charts/appchart
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: flux-system
      valuesFiles:
        - ./values_prod.yaml
