apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helmapp
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/appchart
      version: 0.1.x
      sourceRef:
        kind: GitRepository
        name: flux-system
      valuesFiles:
        - values.yaml
