apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeploy
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: appapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SNAME
              value: {{ .Values.sname }}
          volumeMounts:
            - name: application-config 
              mountPath: "/app/config" 
              readOnly: true
      volumes:
      - name: application-config
        configMap:
          name: api-configmap
          items:
          - key: application.yaml 
            path: application.yaml
