apiVersion: v1
kind: Service
metadata:
  name: appsvc
  labels:
    app: apisvc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: apiport
  selector:
    app: api
