{{- if .Values.serviceAccount.create -}}
# ---
# kind: Role
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: namespace-reader
# rules:
#   - apiGroups: [""]
#     resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
#     verbs: ["get", "list", "watch"]
# ---
# kind: RoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: namespace-reader-binding
# subjects:
# - kind: ServiceAccount
#   name: default
#   apiGroup: ""
# roleRef:
#   kind: Role
#   name: namespace-reader
#   apiGroup: ""
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: service-reader-pod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: discoverns
{{- end }}
