apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealedsecrets
  namespace: argocd
spec:
  destination:
    namespace: sealedsecrets
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: sealed-secrets
    helm:
      values: |-
        commandArgs: 
          - "--update-status"
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: 1.16.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
