---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helmapp-desa
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: helm-ns-desa
  chart:
    spec:
      chart: ./charts/appchart
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: flux-system
      valuesFiles:
        - ./charts/appchart/values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helmapp-prod
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: helm-ns-prod
  chart:
    spec:
      chart: ./charts/appchart
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: flux-system
      valuesFiles:
        - ./charts/appchart/values_prod.yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: helm-img-repo
  namespace: flux-system
spec:
  image: docker.io/ealen/echo-server
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: helm-img-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: helm-img-repo
  policy:
    semver:
      range: 0.5.x