mychart:
  environment:
    - name: OTHER_VAR
      value: desavalue22
    - name: DEMO_VAR
      value: desavalue
    - name: MI_SECRETO
      valueFrom:
        secretKeyRef:
          name: helm-secret-desa
          key: secreto
  prefixName: helm-
  suffixName: -desa
  demoImage: docker.io/ealen/echo-server:0.4.3 # {"$imagepolicy": "flux-system:helm-img-policy-desa"}
