mychart:
  environment:
    - name: DEMO_VAR
      value: prodvalue
    - name: MI_SECRETO
      valueFrom:
        secretKeyRef:
          name: helm-secret-prod
          key: secreto
  prefixName: helm-
  suffixName: -prod
