mychart:
  environment:
    - name: DEMO_VAR
      value: hola
    - name: MI_SECRETO
      valueFrom:
        secretKeyRef:
          name: helm-secret-desa
          key: secreto
  prefixName: helm-
  suffixName: -desa
