# Default values for sbapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.io/yoanyo/springboot-oidc-api
  tag: "1.0"

service:
  type: ClusterIP
  port: 80

sname: api1